// Constants

export const DEFAULT_PAPER_BALANCE = 10000; // USDT
export const PAGE_SIZE = 20;

export const SYMBOLS = [
  'BTCUSDT',
  'ETHUSDT',
  'SOLUSDT',
  'BNBUSDT',
  'XRPUSDT',
  'ADAUSDT',
  'DOGEUSDT',
  'AVAXUSDT',
  'DOTUSDT',
  'MATICUSDT',
  // +50 coins
  'TRXUSDT',
  'LINKUSDT',
  'UNIUSDT',
  'ATOMUSDT',
  'LTCUSDT',
  'BCHUSDT',
  'FILUSDT',
  'APTUSDT',
  'SUIUSDT',
  'ARBUSDT',
  'OPUSDT',
  'NEARUSDT',
  'ICPUSDT',
  'HBARUSDT',
  'XLMUSDT',
  'VETUSDT',
  'THETAUSDT',
  'FTMUSDT',
  'EOSUSDT',
  'AAVEUSDT',
  'MKRUSDT',
  'CRVUSDT',
  'ENJUSDT',
  'MANAUSDT',
  'SANDUSDT',
  'AXSUSDT',
  'CHZUSDT',
  'ZILUSDT',
  'KAVAUSDT',
  'ALGOUSDT',
  'XTZUSDT',
  'NEOUSDT',
  'IOTAUSDT',
  'WAVESUSDT',
  'ZECUSDT',
  'DASHUSDT',
  'RVNUSDT',
  'BATUSDT',
  'ZRXUSDT',
  'STORJUSDT',
  'ANKRUSDT',
  'LDOUSDT',
  'GRTUSDT',
  'FETUSDT',
  'RNDRUSDT',
  'FLOWUSDT',
  'MINAUSDT',
  'CELOUSDT',
  'DYDXUSDT',
  'INJUSDT',
] as const;

export const SYMBOL_INFO: Record<string, { base: string; quote: string; name: string }> = {
  BTCUSDT: { base: 'BTC', quote: 'USDT', name: 'Bitcoin' },
  ETHUSDT: { base: 'ETH', quote: 'USDT', name: 'Ethereum' },
  SOLUSDT: { base: 'SOL', quote: 'USDT', name: 'Solana' },
  BNBUSDT: { base: 'BNB', quote: 'USDT', name: 'Binance Coin' },
  XRPUSDT: { base: 'XRP', quote: 'USDT', name: 'Ripple' },
  ADAUSDT: { base: 'ADA', quote: 'USDT', name: 'Cardano' },
  DOGEUSDT: { base: 'DOGE', quote: 'USDT', name: 'Dogecoin' },
  AVAXUSDT: { base: 'AVAX', quote: 'USDT', name: 'Avalanche' },
  DOTUSDT: { base: 'DOT', quote: 'USDT', name: 'Polkadot' },
  MATICUSDT: { base: 'MATIC', quote: 'USDT', name: 'Polygon' },
  TRXUSDT: { base: 'TRX', quote: 'USDT', name: 'TRON' },
  LINKUSDT: { base: 'LINK', quote: 'USDT', name: 'Chainlink' },
  UNIUSDT: { base: 'UNI', quote: 'USDT', name: 'Uniswap' },
  ATOMUSDT: { base: 'ATOM', quote: 'USDT', name: 'Cosmos' },
  LTCUSDT: { base: 'LTC', quote: 'USDT', name: 'Litecoin' },
  BCHUSDT: { base: 'BCH', quote: 'USDT', name: 'Bitcoin Cash' },
  FILUSDT: { base: 'FIL', quote: 'USDT', name: 'Filecoin' },
  APTUSDT: { base: 'APT', quote: 'USDT', name: 'Aptos' },
  SUIUSDT: { base: 'SUI', quote: 'USDT', name: 'Sui' },
  ARBUSDT: { base: 'ARB', quote: 'USDT', name: 'Arbitrum' },
  OPUSDT: { base: 'OP', quote: 'USDT', name: 'Optimism' },
  NEARUSDT: { base: 'NEAR', quote: 'USDT', name: 'NEAR Protocol' },
  ICPUSDT: { base: 'ICP', quote: 'USDT', name: 'Internet Computer' },
  HBARUSDT: { base: 'HBAR', quote: 'USDT', name: 'Hedera' },
  XLMUSDT: { base: 'XLM', quote: 'USDT', name: 'Stellar' },
  VETUSDT: { base: 'VET', quote: 'USDT', name: 'VeChain' },
  THETAUSDT: { base: 'THETA', quote: 'USDT', name: 'Theta' },
  FTMUSDT: { base: 'FTM', quote: 'USDT', name: 'Fantom' },
  EOSUSDT: { base: 'EOS', quote: 'USDT', name: 'EOS' },
  AAVEUSDT: { base: 'AAVE', quote: 'USDT', name: 'Aave' },
  MKRUSDT: { base: 'MKR', quote: 'USDT', name: 'Maker' },
  CRVUSDT: { base: 'CRV', quote: 'USDT', name: 'Curve DAO' },
  ENJUSDT: { base: 'ENJ', quote: 'USDT', name: 'Enjin' },
  MANAUSDT: { base: 'MANA', quote: 'USDT', name: 'Decentraland' },
  SANDUSDT: { base: 'SAND', quote: 'USDT', name: 'The Sandbox' },
  AXSUSDT: { base: 'AXS', quote: 'USDT', name: 'Axie Infinity' },
  CHZUSDT: { base: 'CHZ', quote: 'USDT', name: 'Chiliz' },
  ZILUSDT: { base: 'ZIL', quote: 'USDT', name: 'Zilliqa' },
  KAVAUSDT: { base: 'KAVA', quote: 'USDT', name: 'Kava' },
  ALGOUSDT: { base: 'ALGO', quote: 'USDT', name: 'Algorand' },
  XTZUSDT: { base: 'XTZ', quote: 'USDT', name: 'Tezos' },
  NEOUSDT: { base: 'NEO', quote: 'USDT', name: 'Neo' },
  IOTAUSDT: { base: 'IOTA', quote: 'USDT', name: 'IOTA' },
  WAVESUSDT: { base: 'WAVES', quote: 'USDT', name: 'Waves' },
  ZECUSDT: { base: 'ZEC', quote: 'USDT', name: 'Zcash' },
  DASHUSDT: { base: 'DASH', quote: 'USDT', name: 'Dash' },
  RVNUSDT: { base: 'RVN', quote: 'USDT', name: 'Ravencoin' },
  BATUSDT: { base: 'BAT', quote: 'USDT', name: 'Basic Attention Token' },
  ZRXUSDT: { base: 'ZRX', quote: 'USDT', name: '0x' },
  STORJUSDT: { base: 'STORJ', quote: 'USDT', name: 'Storj' },
  ANKRUSDT: { base: 'ANKR', quote: 'USDT', name: 'Ankr' },
  LDOUSDT: { base: 'LDO', quote: 'USDT', name: 'Lido DAO' },
  GRTUSDT: { base: 'GRT', quote: 'USDT', name: 'The Graph' },
  FETUSDT: { base: 'FET', quote: 'USDT', name: 'Fetch.ai' },
  RNDRUSDT: { base: 'RNDR', quote: 'USDT', name: 'Render' },
  FLOWUSDT: { base: 'FLOW', quote: 'USDT', name: 'Flow' },
  MINAUSDT: { base: 'MINA', quote: 'USDT', name: 'Mina' },
  CELOUSDT: { base: 'CELO', quote: 'USDT', name: 'Celo' },
  DYDXUSDT: { base: 'DYDX', quote: 'USDT', name: 'dYdX' },
  INJUSDT: { base: 'INJ', quote: 'USDT', name: 'Injective' },
};

export const KLINE_INTERVALS = ['1m', '5m', '15m', '1h', '4h', '1D'] as const;

export const BINANCE_WS_BASE = 'wss://stream.binance.com:9443/ws';
export const BINANCE_TESTNET_WS_BASE = 'wss://testnet.binance.vision/ws';
export const BINANCE_API_BASE = 'https://api.binance.com';
export const BINANCE_TESTNET_API_BASE = 'https://testnet.binance.vision';

export const COLORS = {
  green: '#22c55e',
  red: '#ef4444',
  background: '#0f172a',
  surface: '#1e293b',
  surfaceLight: '#334155',
  text: '#f8fafc',
  textSecondary: '#94a3b8',
  border: '#334155',
};
